services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
    # Ajuda o Hot Reload a funcionar no Windows/Mac
      - WATCHPACK_POLLING=true